name: Deploy Addon

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Package Addon
        uses: BigWigsMods/packager@master
        with:
          args: "-g"
        env:
          CF_API_KEY: ${{ secrets.CF_API_KEY }}
          WAGO_API_TOKEN: ${{ secrets.WAGO_API_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create Clean Zip
        run: |
          rm -rf .release/mshFrames/.github
          rm -rf .release/mshFrames/.vscode
          rm -rf .release/mshFrames/.gitignore
          rm -rf .release/mshFrames/.pkgmeta
          
          cd .release
          zip -r ../mshFrames.zip mshFrames
          cd ..

      - name: Upload to GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          files: mshFrames.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}